management:
    metrics:
        tags:
            application: ${spring.application.name}
    endpoints:
        web:
            exposure:
                include: [ "*","prometheus" ]
    endpoint:
        health:
        show-details: always                
amazonsqs:
    queueName: MessageQueue.fifo