name: Build Project Data Web
run-name: ${{ github.actor }} is building ${{ github.repository }}
on:
  push:
    branches:
      - develop
jobs:      
  run-data-web-project-action:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: 'pom.xml' # optional
        
    - name: Run Unit tests using Maven
      shell: bash
      run: |
            mvn clean test
            ls -ltr .
            ls -ltr target/*
      env:
          DATA_ANALYSER_ENDPOINTS: ${{ vars.DATA_ANALYSER_ENDPOINTS }}            
    - name: Publish Unit Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        check_name: Unit Test Reports      
        detailed_summary: true
    - name: Run Integration tests using Maven
      run: |
            mvn clean verify
            ls -ltr .
            ls -ltr target/*
      env:
          DATA_ANALYSER_ENDPOINTS: ${{ vars.DATA_ANALYSER_ENDPOINTS }}            
    - name: Publish Integration Test Report
      uses: scacap/action-surefire-report@v1 
      with:
        report_paths: '**/target/failsafe-reports/TEST-*.xml'
        check_name: Integration Test Reports        
        detailed_summary: true
    - name: Run Package and Install
      run: |
            mvn clean -DskipTests=true install 
            ls -ltr .
            ls -ltr target/*
            zip -r deploy.zip target/dataweb-1.0.jar   
            cp target/dataweb-1.0.jar .
            ls -ltr .
    - run: echo VERS=$(date +%s) >> $GITHUB_ENV
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v22
      with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: TestWebApp
          environment_name: datawebapp
          version_label: ${{ env.VERS }}
          region: us-east-1
          deployment_package: dataweb-1.0.jar     
