name: Build Project Data Web1
run-name: ${{ github.actor }} is building ${{ github.repository }}
on: [push]
jobs:
  run-data-web-project-action:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: 'pom.xml' # optional
        
    - name: Run Unit tests using Maven
      shell: bash
      run: |
            mvn clean test
            ls -ltr .
            ls -ltr target/*
    - name: Publish Unit Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
    - name: Run Integration tests using Maven
      run: mvn clean failsafe:integration-test
    - name: Publish Integration Test Report
      uses: scacap/action-surefire-report@v1           
    - name: Run Package and Install
      run: mvn clean install
