name: Build Project Data Web
run-name: ${{ github.actor }} is building ${{ github.repository }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: 'pom.xml' # optional
        
    - name: Set and Retrieve Github ENV variables
      shell: bash
      run: |
          # define variables      
          tests=16
          failures=2
    
          # set them as GitHub ENV variables
          echo "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ env.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
    
          # retrieve these GitHub ENV variables
          echo "${{ env.AWS_ACCESS_KEY_ID }} out of ${{ env.AWS_ACCESS_KEY_ID }} tests failed on CI" 
          mvn -DAWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} -DAWS_ACCESS_KEY_ID=${{ env.AWS_SECRET_ACCESS_KEY }}  test
    - name: Run Integration tests using Maven
      run: mvn clean failsafe:integration-test
    - name: Run Package and Install
      run: mvn clean install
