name: Build Project Data Web
run-name: ${{ github.actor }} is building ${{ github.repository }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: 'pom.xml' # optional
    - name: Run Unit tests using Maven
      run: |
           echo "repository variable : $AWS_ACCESS_KEY_ID"
           echo "repository variable : $AWS_SECRET_ACCESS_KEY"
           echo "repository variable : ${{ env.AWS_ACCESS_KEY_ID }} "
           echo "repository variable : ${{ env.AWS_SECRET_ACCESS_KEY }} "
           
           mvn test
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
    - name: Run Integration tests using Maven
      run: mvn clean failsafe:integration-test
    - name: Run Package and Install
      run: mvn clean install
